name: SipZy
description: A beverage discovery and rating platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  http: ^1.2.0
  supabase_flutter: ^2.5.0
  url_launcher: ^6.2.0
  image_picker: ^1.0.7
  image: ^4.1.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.14.4
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.7.0
  path: ^1.8.3

fonts:
  - family: SpaceGrotesk
    fonts:
      - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        weight: 400
      - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        weight: 500
      - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        weight: 700

  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/SipZy_Logo.png"
